---
  - name: Create directories for logbak
    file:
      dest: "{{ item }}"
      state: directory
      owner: myuser
      group: myuser
    with_items:
      - /opt/logbak/
      - /opt/logbak/conf.d/
      - /opt/logbak/reports

  - name: copy logbak.py to /opt/logbak
    copy:
      src: "{{ role_path }}/files/logbak.py"
      dest: /opt/logbak/logbak.py
      owner: myuser
      group: myuser
      mode: 0755

### EXAMPLE
  - name: Copy logbak config - tomcat
    template:
      src: tomcat.conf.j2
      dest: /opt/logbak/conf.d/tomcat.conf
      owner: myuser
      group: myuser
    when: "'tomcat' in group_names"

  - name: Assemble different configs into 1 file
    assemble:
      src: /opt/logbak/conf.d/
      dest: /opt/logbak/logbak.conf

  - name: Setup cron to run logbak.py at 10pm
    cron:
      name: "Run logbak.py"
      user: myuser
      hour: "22"
      minute: "00"
      job: "/opt/logbak/logbak.py"
